[2023-07-10T12:17:31.899+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.replace_questionmarks manual__2023-07-10T12:17:16.950257+00:00 [queued]>
[2023-07-10T12:17:31.914+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.replace_questionmarks manual__2023-07-10T12:17:16.950257+00:00 [queued]>
[2023-07-10T12:17:31.915+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-10T12:17:31.950+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): replace_questionmarks> on 2023-07-10 12:17:16.950257+00:00
[2023-07-10T12:17:31.979+0000] {standard_task_runner.py:57} INFO - Started process 1103 to run task
[2023-07-10T12:17:31.988+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'thyroid_preprocessing_DAG', 'replace_questionmarks', 'manual__2023-07-10T12:17:16.950257+00:00', '--job-id', '205', '--raw', '--subdir', 'DAGS_FOLDER/preprocess_dagfile.py', '--cfg-path', '/tmp/tmp_wv3copu']
[2023-07-10T12:17:31.989+0000] {standard_task_runner.py:85} INFO - Job 205: Subtask replace_questionmarks
[2023-07-10T12:17:32.105+0000] {task_command.py:410} INFO - Running <TaskInstance: thyroid_preprocessing_DAG.replace_questionmarks manual__2023-07-10T12:17:16.950257+00:00 [running]> on host 6998c1ab8829
[2023-07-10T12:17:32.277+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='damirbogdan39@gmail.com' AIRFLOW_CTX_DAG_OWNER='aiflow' AIRFLOW_CTX_DAG_ID='thyroid_preprocessing_DAG' AIRFLOW_CTX_TASK_ID='replace_questionmarks' AIRFLOW_CTX_EXECUTION_DATE='2023-07-10T12:17:16.950257+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-10T12:17:16.950257+00:00'
[2023-07-10T12:17:32.297+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/data/replace_questionmarks.py", line 14, in replace_questionmarks
    df.replace("?", np.nan, inplace=True)
AttributeError: 'NoneType' object has no attribute 'replace'
[2023-07-10T12:17:32.309+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=thyroid_preprocessing_DAG, task_id=replace_questionmarks, execution_date=20230710T121716, start_date=20230710T121731, end_date=20230710T121732
[2023-07-10T12:17:32.327+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 205 for task replace_questionmarks ('NoneType' object has no attribute 'replace'; 1103)
[2023-07-10T12:17:32.379+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-10T12:17:32.420+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
