[2023-07-10T12:04:36.309+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.import_source_2 manual__2023-07-10T12:04:32.882688+00:00 [queued]>
[2023-07-10T12:04:36.381+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.import_source_2 manual__2023-07-10T12:04:32.882688+00:00 [queued]>
[2023-07-10T12:04:36.382+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-10T12:04:36.431+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): import_source_2> on 2023-07-10 12:04:32.882688+00:00
[2023-07-10T12:04:36.453+0000] {standard_task_runner.py:57} INFO - Started process 836 to run task
[2023-07-10T12:04:36.480+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'thyroid_preprocessing_DAG', 'import_source_2', 'manual__2023-07-10T12:04:32.882688+00:00', '--job-id', '198', '--raw', '--subdir', 'DAGS_FOLDER/preprocess_dagfile.py', '--cfg-path', '/tmp/tmph09r2qqk']
[2023-07-10T12:04:36.489+0000] {standard_task_runner.py:85} INFO - Job 198: Subtask import_source_2
[2023-07-10T12:04:36.675+0000] {task_command.py:410} INFO - Running <TaskInstance: thyroid_preprocessing_DAG.import_source_2 manual__2023-07-10T12:04:32.882688+00:00 [running]> on host 6998c1ab8829
[2023-07-10T12:04:37.005+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='damirbogdan39@gmail.com' AIRFLOW_CTX_DAG_OWNER='aiflow' AIRFLOW_CTX_DAG_ID='thyroid_preprocessing_DAG' AIRFLOW_CTX_TASK_ID='import_source_2' AIRFLOW_CTX_EXECUTION_DATE='2023-07-10T12:04:32.882688+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-10T12:04:32.882688+00:00'
[2023-07-10T12:04:37.266+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/data/import_source_2.py", line 16, in import_source_2
    df_source_2 = pd.read_parquet(file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 500, in read_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 240, in read
    path_or_handle, columns=columns, **kwargs
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet/core.py", line 2939, in read_table
    thrift_container_size_limit=thrift_container_size_limit,
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet/core.py", line 2466, in __init__
    [fragment], schema=schema or fragment.physical_schema,
  File "pyarrow/_dataset.pyx", line 1004, in pyarrow._dataset.Fragment.physical_schema.__get__
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Could not open Parquet input source '<Buffer>': Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.
[2023-07-10T12:04:37.321+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=thyroid_preprocessing_DAG, task_id=import_source_2, execution_date=20230710T120432, start_date=20230710T120436, end_date=20230710T120437
[2023-07-10T12:04:37.381+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 198 for task import_source_2 (Could not open Parquet input source '<Buffer>': Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.; 836)
[2023-07-10T12:04:37.442+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-10T12:04:37.563+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
